# Define locations for which builds should be created.
# For each build we specify a subsampling scheme via an explicit key.
builds:

  colorado:
    subsampling_scheme: state
    country: USA
    division: Colorado

  coloradous:
    subsampling_scheme: state-us
    country: USA
    division: Colorado


subsampling:

  state:
    focal:
      group_by: "year month"
      max_sequences: 1500
      query: --query "country == '{country}' and division == '{division}'"

  state-us:
    focal:
      group_by: "year month"
      max_sequences: 1500
      query: --query "country == '{country}' and division == '{division}'"

    national-context:
      group_by: "usa_region year month"
      seq_per_group: 20
      query: --query "country == '{country}' and division != '{division}'"
    


   
